// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RideManager.Data;

#nullable disable

namespace RideManager.Data.Migrations
{
    [DbContext(typeof(RideManagerDbContext))]
    [Migration("20260531133902_InitialDatabaseModel")]
    partial class InitialDatabaseModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RideManager.Data.ActuatorCommandEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActuatorName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("actuator_name");

                    b.Property<string>("CommandType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("command_type");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<Guid?>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("error_message");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload_json");

                    b.Property<DateTimeOffset>("RequestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("requested_at");

                    b.Property<Guid?>("SafetyDecisionId")
                        .HasColumnType("uuid")
                        .HasColumnName("safety_decision_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("p_k_actuator_commands");

                    b.HasIndex("DeviceId")
                        .HasDatabaseName("i_x_actuator_commands_device_id");

                    b.HasIndex("SafetyDecisionId")
                        .HasDatabaseName("i_x_actuator_commands_safety_decision_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("i_x_actuator_commands_status");

                    b.HasIndex("ActuatorName", "RequestedAt")
                        .HasDatabaseName("i_x_actuator_commands_actuator_name_requested_at");

                    b.ToTable("actuator_commands", (string)null);
                });

            modelBuilder.Entity("RideManager.Data.CameraFindingEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<double?>("BoxHeight")
                        .HasColumnType("double precision")
                        .HasColumnName("box_height");

                    b.Property<double?>("BoxWidth")
                        .HasColumnType("double precision")
                        .HasColumnName("box_width");

                    b.Property<double?>("BoxX")
                        .HasColumnType("double precision")
                        .HasColumnName("box_x");

                    b.Property<double?>("BoxY")
                        .HasColumnType("double precision")
                        .HasColumnName("box_y");

                    b.Property<Guid?>("CameraFrameId")
                        .HasColumnType("uuid")
                        .HasColumnName("camera_frame_id");

                    b.Property<string>("CameraId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("camera_id");

                    b.Property<double>("Confidence")
                        .HasColumnType("double precision")
                        .HasColumnName("confidence");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("label");

                    b.Property<DateTimeOffset>("ObservedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("observed_at");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload_json");

                    b.Property<Guid>("SafetyDecisionId")
                        .HasColumnType("uuid")
                        .HasColumnName("safety_decision_id");

                    b.HasKey("Id")
                        .HasName("p_k_camera_findings");

                    b.HasIndex("CameraFrameId")
                        .HasDatabaseName("i_x_camera_findings_camera_frame_id");

                    b.HasIndex("Label")
                        .HasDatabaseName("i_x_camera_findings_label");

                    b.HasIndex("SafetyDecisionId")
                        .HasDatabaseName("i_x_camera_findings_safety_decision_id");

                    b.HasIndex("CameraId", "ObservedAt")
                        .HasDatabaseName("i_x_camera_findings_camera_id_observed_at");

                    b.ToTable("camera_findings", (string)null);
                });

            modelBuilder.Entity("RideManager.Data.CameraFrameEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CameraId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("camera_id");

                    b.Property<double?>("CaptureLatencyMs")
                        .HasColumnType("double precision")
                        .HasColumnName("capture_latency_ms");

                    b.Property<DateTimeOffset>("CapturedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("captured_at");

                    b.Property<Guid?>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<long?>("DroppedFrames")
                        .HasColumnType("bigint")
                        .HasColumnName("dropped_frames");

                    b.Property<double?>("Fps")
                        .HasColumnType("double precision")
                        .HasColumnName("fps");

                    b.Property<int?>("Height")
                        .HasColumnType("integer")
                        .HasColumnName("height");

                    b.Property<double?>("InferenceLatencyMs")
                        .HasColumnType("double precision")
                        .HasColumnName("inference_latency_ms");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata_json");

                    b.Property<double?>("PreprocessLatencyMs")
                        .HasColumnType("double precision")
                        .HasColumnName("preprocess_latency_ms");

                    b.Property<Guid?>("SafetyDecisionId")
                        .HasColumnType("uuid")
                        .HasColumnName("safety_decision_id");

                    b.Property<double?>("TotalLatencyMs")
                        .HasColumnType("double precision")
                        .HasColumnName("total_latency_ms");

                    b.Property<int?>("Width")
                        .HasColumnType("integer")
                        .HasColumnName("width");

                    b.HasKey("Id")
                        .HasName("p_k_camera_frames");

                    b.HasIndex("DeviceId")
                        .HasDatabaseName("i_x_camera_frames_device_id");

                    b.HasIndex("SafetyDecisionId")
                        .HasDatabaseName("i_x_camera_frames_safety_decision_id");

                    b.HasIndex("CameraId", "CapturedAt")
                        .HasDatabaseName("i_x_camera_frames_camera_id_captured_at");

                    b.ToTable("camera_frames", (string)null);
                });

            modelBuilder.Entity("RideManager.Data.DeviceEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("address");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<string>("ConfigJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("config_json");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DeviceType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("device_type");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<string>("Transport")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("transport");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_devices");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("i_x_devices_code");

                    b.ToTable("devices", (string)null);
                });

            modelBuilder.Entity("RideManager.Data.ModelArtifactEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Backend")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("backend");

                    b.Property<string>("ConfigJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("config_json");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("InputHeight")
                        .HasColumnType("integer")
                        .HasColumnName("input_height");

                    b.Property<int?>("InputWidth")
                        .HasColumnType("integer")
                        .HasColumnName("input_width");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("LabelsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("labels_json");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("relative_path");

                    b.Property<string>("Version")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("p_k_model_artifacts");

                    b.HasIndex("Name", "Backend", "Version")
                        .HasDatabaseName("i_x_model_artifacts_name_backend_version");

                    b.ToTable("model_artifacts", (string)null);
                });

            modelBuilder.Entity("RideManager.Data.RunSessionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ConfigJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("config_json");

                    b.Property<string>("HostName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("host_name");

                    b.Property<string>("Note")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("note");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<DateTimeOffset?>("StoppedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("stopped_at");

                    b.HasKey("Id")
                        .HasName("p_k_run_sessions");

                    b.HasIndex("StartedAt")
                        .HasDatabaseName("i_x_run_sessions_started_at");

                    b.ToTable("run_sessions", (string)null);
                });

            modelBuilder.Entity("RideManager.Data.SafetyDecisionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("DecidedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("decided_at");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload_json");

                    b.Property<string>("RiskLevel")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("risk_level");

                    b.Property<Guid?>("RunSessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("run_session_id");

                    b.HasKey("Id")
                        .HasName("p_k_safety_decisions");

                    b.HasIndex("DecidedAt")
                        .HasDatabaseName("i_x_safety_decisions_decided_at");

                    b.HasIndex("RiskLevel")
                        .HasDatabaseName("i_x_safety_decisions_risk_level");

                    b.HasIndex("RunSessionId")
                        .HasDatabaseName("i_x_safety_decisions_run_session_id");

                    b.ToTable("safety_decisions", (string)null);
                });

            modelBuilder.Entity("RideManager.Data.SensorReadingEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Metric")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("metric");

                    b.Property<Guid>("SensorSnapshotId")
                        .HasColumnType("uuid")
                        .HasColumnName("sensor_snapshot_id");

                    b.Property<string>("Unit")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("unit");

                    b.Property<double>("Value")
                        .HasColumnType("double precision")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("p_k_sensor_readings");

                    b.HasIndex("Metric")
                        .HasDatabaseName("i_x_sensor_readings_metric");

                    b.HasIndex("SensorSnapshotId")
                        .HasDatabaseName("i_x_sensor_readings_sensor_snapshot_id");

                    b.ToTable("sensor_readings", (string)null);
                });

            modelBuilder.Entity("RideManager.Data.SensorSnapshotEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<DateTimeOffset>("ObservedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("observed_at");

                    b.Property<Guid>("SafetyDecisionId")
                        .HasColumnType("uuid")
                        .HasColumnName("safety_decision_id");

                    b.Property<string>("SensorName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("sensor_name");

                    b.Property<string>("ValuesJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("values_json");

                    b.HasKey("Id")
                        .HasName("p_k_sensor_snapshots");

                    b.HasIndex("DeviceId")
                        .HasDatabaseName("i_x_sensor_snapshots_device_id");

                    b.HasIndex("SafetyDecisionId")
                        .HasDatabaseName("i_x_sensor_snapshots_safety_decision_id");

                    b.HasIndex("SensorName", "ObservedAt")
                        .HasDatabaseName("i_x_sensor_snapshots_sensor_name_observed_at");

                    b.ToTable("sensor_snapshots", (string)null);
                });

            modelBuilder.Entity("RideManager.Data.SystemEventEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("level");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("message");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload_json");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("source");

                    b.HasKey("Id")
                        .HasName("p_k_system_events");

                    b.HasIndex("Level")
                        .HasDatabaseName("i_x_system_events_level");

                    b.HasIndex("Source", "OccurredAt")
                        .HasDatabaseName("i_x_system_events_source_occurred_at");

                    b.ToTable("system_events", (string)null);
                });

            modelBuilder.Entity("RideManager.Data.ActuatorCommandEntity", b =>
                {
                    b.HasOne("RideManager.Data.DeviceEntity", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("f_k_actuator_commands_devices_device_id");

                    b.HasOne("RideManager.Data.SafetyDecisionEntity", "SafetyDecision")
                        .WithMany("ActuatorCommands")
                        .HasForeignKey("SafetyDecisionId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("f_k_actuator_commands_safety_decisions_safety_decision_id");

                    b.Navigation("Device");

                    b.Navigation("SafetyDecision");
                });

            modelBuilder.Entity("RideManager.Data.CameraFindingEntity", b =>
                {
                    b.HasOne("RideManager.Data.CameraFrameEntity", "CameraFrame")
                        .WithMany("Findings")
                        .HasForeignKey("CameraFrameId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("f_k_camera_findings_camera_frames_camera_frame_id");

                    b.HasOne("RideManager.Data.SafetyDecisionEntity", "SafetyDecision")
                        .WithMany("CameraFindings")
                        .HasForeignKey("SafetyDecisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_camera_findings_safety_decisions_safety_decision_id");

                    b.Navigation("CameraFrame");

                    b.Navigation("SafetyDecision");
                });

            modelBuilder.Entity("RideManager.Data.CameraFrameEntity", b =>
                {
                    b.HasOne("RideManager.Data.DeviceEntity", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("f_k_camera_frames_devices_device_id");

                    b.HasOne("RideManager.Data.SafetyDecisionEntity", "SafetyDecision")
                        .WithMany("CameraFrames")
                        .HasForeignKey("SafetyDecisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("f_k_camera_frames_safety_decisions_safety_decision_id");

                    b.Navigation("Device");

                    b.Navigation("SafetyDecision");
                });

            modelBuilder.Entity("RideManager.Data.SafetyDecisionEntity", b =>
                {
                    b.HasOne("RideManager.Data.RunSessionEntity", "RunSession")
                        .WithMany()
                        .HasForeignKey("RunSessionId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("f_k_safety_decisions_run_sessions_run_session_id");

                    b.Navigation("RunSession");
                });

            modelBuilder.Entity("RideManager.Data.SensorReadingEntity", b =>
                {
                    b.HasOne("RideManager.Data.SensorSnapshotEntity", "SensorSnapshot")
                        .WithMany("Readings")
                        .HasForeignKey("SensorSnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_sensor_readings_sensor_snapshots_sensor_snapshot_id");

                    b.Navigation("SensorSnapshot");
                });

            modelBuilder.Entity("RideManager.Data.SensorSnapshotEntity", b =>
                {
                    b.HasOne("RideManager.Data.DeviceEntity", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("f_k_sensor_snapshots_devices_device_id");

                    b.HasOne("RideManager.Data.SafetyDecisionEntity", "SafetyDecision")
                        .WithMany("SensorSnapshots")
                        .HasForeignKey("SafetyDecisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_sensor_snapshots_safety_decisions_safety_decision_id");

                    b.Navigation("Device");

                    b.Navigation("SafetyDecision");
                });

            modelBuilder.Entity("RideManager.Data.CameraFrameEntity", b =>
                {
                    b.Navigation("Findings");
                });

            modelBuilder.Entity("RideManager.Data.SafetyDecisionEntity", b =>
                {
                    b.Navigation("ActuatorCommands");

                    b.Navigation("CameraFindings");

                    b.Navigation("CameraFrames");

                    b.Navigation("SensorSnapshots");
                });

            modelBuilder.Entity("RideManager.Data.SensorSnapshotEntity", b =>
                {
                    b.Navigation("Readings");
                });
#pragma warning restore 612, 618
        }
    }
}
